### ISSUE TITLE
Application Context Refinements

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#171]
Some small refinements are needed for the Application Context support:

- [ ] The option "showAddAsAnnotation": false in Measure tool does not works. The administrator should be able to put the following configuration inside the configuration text area and obtain the expected result that is disabling the functionality to convert a measurement to an annotation

```
{
                  "defaultOptions": {
                    "showAddAsAnnotation": false
                  }
}
```

- [ ] Copying the context share URL the tooltip is not centered. The same for all resource types, issue of the share button

![image](https://user-images.githubusercontent.com/1280027/74549465-f898de00-4f4f-11ea-9b00-180c52ffb8bf.png)

- [ ] I can copy and paste a context title with spaces and then save

![image](https://user-images.githubusercontent.com/1280027/74549415-e454e100-4f4f-11ea-8d75-080a3e7eaddc.png)

- [ ] The position of the wizard close button should be changed. A new **Close** button in the bottom right toolbar should be included, once clicked the same functionalities of the existing close button on top left corner of the wizard must be maintained:

![context_close_button](https://user-images.githubusercontent.com/1280027/74549331-c25b5e80-4f4f-11ea-9ff4-4f265f0af13a.png)

- [ ] Impossible to remove **all plugins** from the rigth list of wizard step #2 while editing an existing contexts (it seems to happen only in geOrchestra MS project):

![plugins_bug](https://user-images.githubusercontent.com/1280027/74548015-52e46f80-4f4d-11ea-8e3d-601e6df2c370.png)

The following error appear in console:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at GeOrchestra.js?b1424bfbffda60471abe:1
    at GeOrchestra.js?b1424bfbffda60471abe:1
    at Array.forEach (<anonymous>)
    at e (GeOrchestra.js?b1424bfbffda60471abe:1)
    at GeOrchestra.js?b1424bfbffda60471abe:1
    at Array.forEach (<anonymous>)
    at t.project (GeOrchestra.js?b1424bfbffda60471abe:1)
    at t._next (GeOrchestra.js?b1424bfbffda60471abe:275)
    at t.next (GeOrchestra.js?b1424bfbffda60471abe:275)
    at t._next (GeOrchestra.js?b1424bfbffda60471abe:275)
    at t.next (GeOrchestra.js?b1424bfbffda60471abe:275)
    at t.next (GeOrchestra.js?b1424bfbffda60471abe:275)
    at GeOrchestra.js?b1424bfbffda60471abe:275
    at GeOrchestra.js?b1424bfbffda60471abe:275
    at GeOrchestra.js?b1424bfbffda60471abe:275
    at GeOrchestra.js?b1424bfbffda60471abe:275
```

- [ ] We can consider to invert steps 2 and 3 of the context wizard having the following final order: General Settings -> Configure Map -> Configure Plugins

**Comment by tdipisa** [comment]
@UMarkau, please review the points in the above description. We can consider to open new issues for each point and connect them to this epic.
