### ISSUE TITLE
MS project update and review

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#72]
Some needed activities to finalize things for phase I and do testing:

- [x] #73 Complete the missing security part to manage LDAP authorizations for MS resources (like app contexts)  
- [x] #74 Provide the needed documentation updates about security  
- [x] #75 Update the Ms revision to latest master
- [x] #75 Finalize CRS configs and PR merge #71 <-- ths is a PR, not part of the epic itself (issues only)
- [x] #75 Review default configuration  like to one of the current georchestra viewer:
       - extent/center of map
       - Deafult backgrounds
       - Default catalog services
       - Default CRS list (we can configure the whole set for testing)
- [x] #75 Remove save button in option menu (this will be re-enabled later for #35)  
- [x] #76 The app context admin UI must appears in the admin section of georchestra SDI
